volumeClaim:
  name: eoepca-userman-pvc
  create: false
config:
  domain: test.kube.5570w.rconway.uk
  volumeClaim:
    name: eoepca-userman-pvc
opendj:
  # This can be useful to workaround helm 'failed to upgrade' errors due to
  # immutable fields in the 'um-login-service-persistence-init-ss' job
  # persistence:
  #   enabled: false
  volumeClaim:
    name: eoepca-userman-pvc
oxauth:
  volumeClaim:
    name: eoepca-userman-pvc
oxtrust:
  volumeClaim:
    name: eoepca-userman-pvc
global:
  domain: test.kube.5570w.rconway.uk
  nginxIp: 172.17.0.1
nginx:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - test.kube.5570w.rconway.uk
    tls:
      - hosts:
          - test.kube.5570w.rconway.uk
        secretName: login-service-tls
