auth:
  rootUser: eoepca
  rootPassword: changeme

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: minio-console.172.17.0.1.nip.io

apiIngress:
  enabled: true
  ingressClassName: nginx
  hostname: minio.172.17.0.1.nip.io

persistence:
  storageClass: local-path

defaultBuckets: "eoepca, fredbob"
